name: fe-resume-pipeline
on:
  push:
    branches: [ main ]
    paths:
      - '4-frontend-resume/**'
      # - '.github/workflows/**'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  Build_FE_Resume:
    runs-on: ubuntu-latest

    steps:

      - name: Set up Git repository
        uses: actions/checkout@v2

      - name: Set up LaTeX
        uses: xu-cheng/latex-action@v2
        with:
          working_directory: 4-frontend-resume
          root_file: main.tex
          args: -jobname=Krishna_Nimbalkar_FE_Resume main.tex

      - name: Copy file
        run: |
          sudo mv 4-frontend-resume/Krishna_Nimbalkar_FE_Resume.pdf pdfjs

      - name: Get current date
        id: date
        run: |
          echo "::set-output name=date::$(date +'%d/%m/%Y')"

      - name: Create Resume Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: FE_Resume_${{ steps.date.outputs.date }}
          release_name: Krishna Nimbalkar FE Resume
          body: |
            Resume Last Updated on : ${{ steps.date.outputs.date }}
          draft: false
          prerelease: false

      - name: Upload Resume Release Asset
        id: upload-release-asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: pdfjs/Krishna_Nimbalkar_FE_Resume.pdf
          asset_name: Krishna_Nimbalkar_FE_Resume.pdf
          asset_content_type: application/pdf

      # - name: Deploy to gh-pages
      #   uses: s0/git-publish-subdir-action@develop
      #   env:
      #     REPO: self
      #     BRANCH: gh-pages
      #     FOLDER: pdfjs
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      #     MESSAGE: "deploy website"